---
# SPDX-License-Identifier: MIT

apiVersion: v2
name: node-local-dns
version: 0.1.0
appVersion: 1.22.23
maintainers:
- name: jkrzemin
  email: jakub.krzeminski@flintwire.com
description: |
 A chart to install node-local-dns.

 NodeLocal DNSCache improves Cluster DNS performance by running a DNS caching agent on cluster nodes as a DaemonSet.
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
keywords:
  - dns
  - node-local-dns
  - networking
sources:
  - https://github.com/jkrzemin/helm-charts
